version: '3.8'
services:
  fita_app_be:
    container_name: shopping_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./:/go/src/github.com/barizalhaq/FITA-shopping-API
    networks:
      - fita_shopping_app
    depends_on:
      - db
      - redis
  db:
    container_name: shopping_api_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - 5432:5432
    networks:
      - fita_shopping_app
    restart: unless-stopped

networks:
  fita_shopping_app:
    driver: bridge

volumes:
  db:
