// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gModel

type AuthenticateInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AuthenticateResponse struct {
	Authenticated bool `json:"authenticated"`
}

type Cart struct {
	ID       int        `json:"ID"`
	Owner    *User      `json:"owner"`
	Products []*Product `json:"products"`
}

type DecartInput struct {
	ProductIDs []int `json:"productIDs"`
}

type DecreaseCartProductQtyInput struct {
	ProductsToAdd []*ProductWithQty `json:"productsToAdd"`
}

type EncartInput struct {
	ProductsToAdd []*ProductWithQty `json:"productsToAdd"`
}

type Invoice struct {
	Cart       *Cart         `json:"cart"`
	TotalPrice *InvoicePrice `json:"total_price"`
}

type InvoicePrice struct {
	OriginalTotalPrice float64 `json:"originalTotalPrice"`
	ActualCurrentPrice float64 `json:"actualCurrentPrice"`
	PriceDiscount      float64 `json:"priceDiscount"`
	Currency           string  `json:"currency"`
}

type Product struct {
	ID    int           `json:"ID"`
	Sku   string        `json:"sku"`
	Name  string        `json:"name"`
	Price *ProductPrice `json:"price"`
	Qty   int           `json:"qty"`
}

type ProductPrice struct {
	OriginalPrice float64 `json:"originalPrice"`
	Currency      string  `json:"currency"`
}

type ProductWithQty struct {
	ProductID int `json:"productID"`
	Qty       int `json:"qty"`
}

type RegisterInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	User *User `json:"user"`
}

type User struct {
	ID       int    `json:"ID"`
	Username string `json:"username"`
}
