name: Latest Build

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run the tests
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: go test -v ./...
  build:
    name: Build latest
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        run: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Setup ENV
        run: |
          BINARY_NAME=${{github.repository}}
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
      - name: Install modules
        run: go mod download
      - name: Build binary
        run: |
          go build -o "$BINARY_NAME" ./server/server.go
